apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::059821202186:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RVJEUEJJNFEN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::059821202186:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: '2022-10-02T12:51:18Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1655'
  uid: faccd7b4-7d0d-49ab-8699-29e6d3106180
